### ISSUE TITLE
WordPress White Screen of Death Error

### ISSUE THREAD

**Issue by creedally** [creedally/creedally_wp#2]
The current setup is showing white blank screen. I did some research found that it can be Plugin or theme conflict. kindly help me with fixing the issue.

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue now has a bounty of $10.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://app.gitcommits.com/issue/wordpress-white-screen-of-death-error).
- Questions? Checkout [GitCommits Help](https://www.gitcommits.com/faq)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://app.gitcommits.com/explorer)

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. Open 2. **Started**  3. Submitted 4. Done

<hr>

**Work has been started.**

**<a href='https://app.gitcommits.com/profile/SapneshNaik'>SapneshNaik</a> has been approved to start work.**

<hr />

**Message:** thanks for the application, kindly initiate the work.


<a href='https://app.gitcommits.com/issue/wordpress-white-screen-of-death-error'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**<a href='https://app.gitcommits.com/profile/SapneshNaik'>SapneshNaik</a> Work has been approved by <a href='https://app.gitcommits.com/profile/creedally2103'>creedally2103</a>.**
<hr />

**Message:** Pull request has been approved, you will receive the payment shortly.


<a href='https://app.gitcommits.com/issue/wordpress-white-screen-of-death-error'>Click Here to view more</a> on GitCommits Bounty detail page.
